openapi: 3.0.1
info:
  title: Printer Service API
  description: Generates documents (odt, docx, doc, pdf) by merging a template (odt, docx, doc) and a data model.
  version: 1.0.0

servers:
  - url: http://printer/v1

tags:
  - name: printer
    description: The printer resource

paths:
  '/print':
    post:
      tags:
        - printer
      summary: Produces a document (odt, docx, doc, pdf) by merging the template and data provided within the PrintMessage
      operationId: print
      requestBody:
        description: A PrintMessage
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PrintMessage'
      responses:
        '201':
          description: Document has been successfully generated
          content:
            application/pdf:
              schema:
                type: string
                format: byte
            'application/vnd.oasis.opendocument.text':
              schema:
                type: string
                format: byte
            'application/vnd.openxmlformats-officedocument.wordprocessingml.document':
              schema:
                type: string
                format: byte
            'application/msword':
              schema:
                type: string
                format: byte
        '400':
          description: Bad request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Template not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Unexpected error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: The Http error code
        message:
          type: string
          description: The reason
    PrintMessage:
      type: object
      required:
        - templateUrl
        - convert
        - data
      properties:
        templateUrl:
          type: string
          description: URL of the template used for the generation. Can be either absolute or relative (to a configured base url).
        convert:
          type: boolean
          description: When true the generated document is converted to pdf.
        data:
          type: object
          description: The data model to merge.
