printer:
  xdoc:
    base-url: classpath:/xdoc
  freemarker:
    base-path: /freemarker
  jasper:
    base-url: classpath:/jasper
    resource-folder: /jasper

#actuator
management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "prometheus"]