printer:
  template:
    base-url: classpath:/
  jasper:
    base-url: classpath:/jasper
    unzip-folder: ./build/generated
    resource-folder: /jasper
    templates:

#actuator
#management.server.port=9090