name: CI

on: [push]

jobs:
  build:
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GPG_KEY: ${{ secrets.GPG_KEY }}
      GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: SetupJava
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Test
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: test
      - name: Build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build -PdockerUsername=$DOCKER_USERNAME -PdockerPassword=$DOCKER_PASSWORD -PsigningKey=$GPG_KEY -PsigningPassword=$GPG_PASSWORD
      - name: Build & deploy image
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: jib

