name: CI

on: [push]

jobs:
  build:
    env:
      dockerUsername: ${{ secrets.DOCKER_USERNAME }}
      dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
      ossrhUserName: ${{ secrets.OSSRH_USERNAME }}
      ossrhPassword: ${{ secrets.OSSRH_PASSWORD }}
      signingKey: ${{ secrets.GPG_KEY }}
      signingPassword: ${{ secrets.GPG_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build Printer API
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: :printer-api:build

      - name: Publish Printer API
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: :printer-api:publish

      - name: Build Printer Server
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: :printer-server:build

      - name: Run Integration Tests
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: :integration-test:build

      - name: Close & Release Repo
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: closeAndReleaseRepository --stacktrace

      - name: Push Docker Image
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: :printer-server:jib

