name: CI

on: [push]

jobs:
  build:
    env:
      dockerUsername: ${{ secrets.DOCKER_USERNAME }}
      dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
      signingKey: ${{ secrets.GPG_KEY }}
      signingPassword: ${{ secrets.GPG_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: SetupJava
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Test
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: test
      - name: Build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
      - name: Build & deploy image
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: jib

