name: CI

on: [push]

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: SetupJava
        uses: actions/setup-java@v1
          with:
            java-version: 11

  test:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Test
        uses: eskatos/gradle-command-action@v1
          with:
            arguments: test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build

  buildImage:
    needs: build
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Jib
        uses: eskatos/gradle-command-action@v1
          with:
            arguments: jib
